set:
  augment: false
  features: false
  train: false
  eval: false
  gpus: 1 # 0 to use CPU

path:
  root_dir: /home/manderson/DCASE2021
  data_dir: ${path.root_dir}/data
  train_dir: ${path.data_dir}/Development_Set/Training_Set
  val_dir:  ${path.data_dir}/Development_Set/Validation_Set
  feat_path: ${path.root_dir}/features
  train_feat: ${path.feat_path}/feat_train
  eval_feat:  ${path.feat_path}/feat_eval
  model: ${path.root_dir}/models
  best_model: ${path.model}/best_model.ckpt
  last_model: ${path.model}/last_model.ckpt

features:

  time_stretch: 0.05
  direction: bidirectional
  seg_len: 0.200
  hop_seg: 0.050
  sample_rate: 22050
  n_fft: 512
  hop: 256

train:
  n_shot: 5
  k_way: 10
  epochs: 100
  lr: 0.001
  momentum: 0.8
  threshold: 0.01
  patience: 5

eval:
  samples_neg: 650
  iterations: 3
  query_batch_size: 8
  negative_set_batch_size : 16
  threshold: 0.55
