set:
  features: false
  train: true
  eval: false

path:
  root_dir: /home/mark/projects/phd/DCASE2021
  train_dir: ${path.root_dir}/data/Development_Set/Training_Set
  val_dir:  ${path.root_dir}/data/Development_Set/Validation_Set
  feat_path: ${path.root_dir}/features
  train_feat: ${path.feat_path}/feat_train
  eval_feat:  ${path.feat_path}/feat_eval
  model: ${path.root_dir}/models
  best_model: ${path.model}/best_model.pth
  last_model: ${path.model}/last_model.pth

features:
  time_stretch: 1.2
  seg_len: 0.200
  hop_seg: 0.050
  sample_rate: 22050
  n_fft: 256
  hop: 128

train:
  device: cuda
  n_shot: 5
  k_way: 10
  epochs: 50
  lr: 0.001
  momentum: 0.9
  threshold: 0.001
  patience: 5